config/routes.rb
Rails.application.routes.draw do
  resources :content_types

  resources :contents do
  member do
    get "vote"
  end
end

  resources :groups

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'groups#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :group
  belongs_to :content_type
  acts_as_votable 
end

app/models/content_type.rb
class ContentType < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy, :vote]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @content.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :description, :filename, :sort_order, :group_id, :thumbnail, :length, :content_type_id)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :filename, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :filename, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sort_order, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :sort_order, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :thumbnail, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :thumbnail, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :length, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :length, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  contents_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/contents/edit.html.erb
<%- model_class = Content -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Content %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contents/index.html.erb
<%- model_class = Content -%>
<div class="page-header">
  <h1><%=t '.title', :default => Content %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:filename) %></th>
      <th><%= model_class.human_attribute_name(:sort_order) %></th>
      <th><%= model_class.human_attribute_name(:thumbnail) %></th>
      <th><%= model_class.human_attribute_name(:length) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.id %></td>
        <td><%= content.title %></td>
        <td><%= content.description %></td>
        <td><%= content.filename %></td>
        <td><%= content.sort_order %></td>
        <td><%= content.thumbnail %></td>
        <td><%= content.length %></td>
        <td><%=l content.created_at, format: :long %></td>
        <td>
          <%= link_to content_path(content), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to content_path(content), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_content_path,
            :class => 'btn btn-primary' %>

app/views/contents/new.html.erb
<%- model_class = Content -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Content %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contents/show.html.erb
<%- model_class = Content -%>
<div class="page-header">
  <h1><%=t '.title', :default => Content %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @content.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @content.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:filename) %></dt>
      <dd><pre class="prettyprint"><%= @content.filename %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sort_order) %></dt>
      <dd><pre class="prettyprint"><%= @content.sort_order %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:thumbnail) %></dt>
      <dd><pre class="prettyprint"><%= @content.thumbnail %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:length) %></dt>
      <dd><pre class="prettyprint"><%= @content.length %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              contents_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_content_path(@content), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              content_path(@content),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>