config/routes.rb
Rails.application.routes.draw do
  resources :content_types

  resources :contents do
  member do
    get "vote"
  end
end

  resources :groups

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'groups#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/content_types_controller.rb
class ContentTypesController < ApplicationController
  before_action :set_content_type, only: [:show, :edit, :update, :destroy]

  # GET /content_types
  # GET /content_types.json
  def index
    @content_types = ContentType.all
  end

  # GET /content_types/1
  # GET /content_types/1.json
  def show
  end

  # GET /content_types/new
  def new
    @content_type = ContentType.new
  end

  # GET /content_types/1/edit
  def edit
  end

  # POST /content_types
  # POST /content_types.json
  def create
    @content_type = ContentType.new(content_type_params)

    respond_to do |format|
      if @content_type.save
        format.html { redirect_to @content_type, notice: 'Content type was successfully created.' }
        format.json { render :show, status: :created, location: @content_type }
      else
        format.html { render :new }
        format.json { render json: @content_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_types/1
  # PATCH/PUT /content_types/1.json
  def update
    respond_to do |format|
      if @content_type.update(content_type_params)
        format.html { redirect_to @content_type, notice: 'Content type was successfully updated.' }
        format.json { render :show, status: :ok, location: @content_type }
      else
        format.html { render :edit }
        format.json { render json: @content_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_types/1
  # DELETE /content_types/1.json
  def destroy
    @content_type.destroy
    respond_to do |format|
      format.html { redirect_to content_types_url, notice: 'Content type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_type
      @content_type = ContentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_type_params
      params.require(:content_type).permit(:name)
    end
end

app/helpers/content_types_helper.rb
module ContentTypesHelper
end

app/views/content_types/_form.html.erb
<%= form_for @content_type, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  content_types_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/content_types/edit.html.erb
<%- model_class = ContentType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ContentType %></h1>
</div>
<%= render :partial => 'form' %>

app/views/content_types/index.html.erb
<%- model_class = ContentType -%>
<div class="page-header">
  <h1><%=t '.title', :default => ContentType %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @content_types.each do |content_type| %>
      <tr>
        <td><%= content_type.id %></td>
        <td><%= content_type.name %></td>
        <td><%=l content_type.created_at, format: :long %></td>
        <td>
          <%= link_to content_type_path(content_type), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to content_type_path(content_type), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_content_type_path,
            :class => 'btn btn-primary' %>

app/views/content_types/new.html.erb
<%- model_class = ContentType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ContentType %></h1>
</div>
<%= render :partial => 'form' %>

app/views/content_types/show.html.erb
<%- model_class = ContentType -%>
<div class="page-header">
  <h1><%=t '.title', :default => ContentType %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @content_type.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              content_types_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_content_type_path(@content_type), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              content_type_path(@content_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>